language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
before_script:
    - chmod -R a+x scripts
script:
    - './scripts/travis-build.sh'
after_success:
    - './scripts/travis-docker-publish.sh'
notifications:
    email: false
    slack:
        secure: 3/mXNRn2P/3xyuJnPB4F+d13lgL1RrIjS5gSXcqAw+boGsTigaBDV07hNqCuRsgNEuZ7+TaRtqA0OwnxQ+7z8xHLN2d1SLGLt3fSCvbprdIOT/r6vYYIJz1XqeZO3O0K79NPxHI5R2qiPULA2DyYqlM2uFyYJJVWBSufmxo0OvAEYgoAEONwtV+Y67lQz2xNp7mdUATIwL2Q4fF38qNgYvxF1MMaDRsJyC6DbfRm/90z1Rvlt4lA3eNOexKJmRSLlZKRLpJEezHEAzJ15+aJ4fSpIvgMpUb8s1CdJNLMUoZ5cVgUaDhV6SyE+fFKYLPFj3EARHwGeYm8VKmYL337ZwRPFN5faafsyl0YDn6shbANw4OyMTarHFmEepsFu0t+0aW3DRSUp0IMMbqY+TT8pjubRH5jal2ZZ9UjqU44UiUYwRwinefb3U76f2xxX2rW7G3MtwpifL/4fB/cA2KTXIx36G0ZIvDn6Urc2eu2rKDUbK8FdZ7Pv9U0Rx4RUW1lCUpn/X8NoPOHTsMWnz0iVDSQ3tH9khiM/N9s/DjDDa8eXQ7a2eYNLI+tTzqBAV9EA+2uOJ20XC+cY/pP+zKqtWt7FPs7VgSg0gucS7KIa8fuqBY2EjjEHQf/6S0IqVy04sLL2f9hoxs7HFYYoJlA5qivkzutNHUCQe73M0NWynQ=
        on_pull_requests: false
