language: csharp
mono: none
sudo: required
services:
    - docker
branches:
    only:
        - master
        - dev
before_script:
    - chmod -R a+x scripts
script:
    - "./scripts/travis-build.sh"
after_success:
    - "./scripts/travis-docker-publish.sh"
notifications:
    email: false
    slack:
        secure: 8Xf1tkbnaVRc8sUGH3cRXddQ7bIkU9Usy3KpBflSxVadRvG4aiP1vIYd1lhYtl+IvqwVtc+kQCKfwJ/lf+AJuSS8Yr4cno/9+ZLa4lG0hD2idj+0O5benYAUeVjETUUXrt+7IyIBszzzD3G8p6v+Bi0Vx6tn4Fl+YH1D9E64R6K5oysDSl2DhE5vYPgMbH402512B7W34HcFN4Xq47x2gUHCOjoSXhUge6o+fQmnsv7C0zkHu0e82aPnYP59CuLCajOOCHYp2WD0yxI9K4ozKxTiYCrwRa087Z5846T4tXetYOyTI4b/GHV6v6AHIwY3SemJ4UDQKbnONq7du+f1MzCdXC34txaZAv2uQEe/zdjuzOb8BewpLxlPNBEhCi6hcr11xrpl7OrwAJjwPGVHzHqh9aSCGxTnk4NMZEKnXkBNFC+sUJVDRPkSHY/4zInpNU9znG0vqdWzgygGs2MjnIddoKe+fIDntWuqhHlqyqU+d1z/wQaZIm72nBk4tXutlghGhcEnJHJ4P/FD9h/+FpvkafycjaIckAHBaNwtgT1ZcIDauDcykmeRYwQ3j/pSrCt38xI/vDqHxTPOPWsY0p+Ct2bdS4AALhNHyq75xaovfbEkPLjGS4T5mBujZoKI08juc+sWENBXSg0hfc8WaoF8JvwnbppTRw1A7/XhGQs=
