version: '3.5'
services:
    api:
        image: ranger.apigateway:dev
        container_name: apigateway
        ports:
            - '7081:8081'
        networks:
            - ranger
            - apigateway

networks:
    ranger:
        name: ranger-network
        external: true
    apigateway:
        name: apigateway-network
        external: true
